# generic:
#   labels:
#     link: ubos-service-service_label
#   annotations: {}
#   extraSelectorLabels: {}
#   podLabels: {}
#   podAnnotations: {}
#   extraVolumes: []
#   extraImagePullSecrets:
#     - name: regcred
# podAffinityPreset: soft
# podAntiAffinityPreset: soft
# nodeAffinityPreset:
#   type: ''
#   key: ''
#   values: []
# releasePrefix: ''
# envs: {}
# envsString: ''
# secretEnvs: {}
# secretEnvsString: ''
# imagePullSecrets: {}
# defaultImage: nodered/node-red
# defaultImageTag: latest
# defaultImagePullPolicy: Always
# deployments:
#   ubos-service-name:
#     labels: {}
#     podLabels: {}
#     securityContext:
#       fsGroup: 1000
#     replicaCount: "1"
#     nodeSelector: {}
#     tolerations: []
#     strategy:
#       type: Recreate
#     extraImagePullSecrets:
#       - name: regcred
#     extraSelectorLabels:
#       app: ubos-service-name
#     serviceAccountName: default
#     containers:
#       - name: ubos-service-name
#         image: betedo/theia-full
#         imageTag: next
#         imagePullPolicy: IfNotPresent
#         env: []
#         envsFromSecret: {}
#         envSecrets: []
#         envsFromConfigmap: {}
#         envConfigmaps: []
#         volumeMounts:
#           - name: theia-dataubos-service-name
#             mountPath: /home/project
#         resources: {}
#     volumes:
#       - type: pvc
#         name: theia-dataubos-service-name
#         items:
#           - key: theia-dataubos-service-name
#             path: theia-dataubos-service-name
# services:
#   ubos-service-name:
#     clusterIP: None
#     ports:
#       - name: http
#         protocol: TCP
#         port: 80
#         targetPort: 3000
#       - name: dev
#         protocol: TCP
#         port: 3001
#         targetPort: 3001
#     extraSelectorLabels:
#       app: ubos-service-name
# ingresses:
#   ubos-service-url:
#     annotations: {}
#     ingressClassName: nginx
#     name: ubos-service-name
#     hosts:
#       - paths:
#           - pathType: Prefix
#             path: /
#             serviceName: ubos-service-name
#             servicePort: http
#     extraTls:
#       - hosts:
#           - ubos-service-url
#         secretName: ubos-service-tls-secret
#   dev-ubos-service-url:
#     annotations: {}
#     ingressClassName: nginx
#     name: dev-ubos-service-name
#     hosts:
#       - paths:
#           - pathType: Prefix
#             path: /
#             serviceName: ubos-service-name
#             servicePort: dev
#     extraTls:
#       - hosts:
#           - dev-ubos-service-url
#         secretName: tls-secret
# secrets:
#   secret-ubos-service-name:
#     type: Opaque
#     data:
#       auth: ubos-service-user-name: Bcrypt.hash(ubos-service-password)
# configMaps: {}
# pvcs:
#   theia-dataubos-service-name:
#     accessModes:
#       - ReadWriteOnce
#     size: 8Gi
# hooks: {}
# cronJobs: {}
# jobs: {}
# serviceMonitors: {}
# diagnosticMode:
#   enbled: false
#   command:
#     - sleep
#   args:
#     - infinity
# extraDeploy: {}
