apiVersion: v2
description: UBOS UI - web user interface builder.
name: UI Editor
icon: https://ubos.tech/wp-content/uploads/2023/11/cbimage-1-jpg.webp
version: 0.0.2
maintainers:
- name: UBOS
  email: ubos@ubos.tech
