# replicaCount: 1
# strategyType: Recreate

# image:
#   repository: eclipse-mosquitto
#   tag: 1.6.12
#   pullPolicy: IfNotPresent

# imagePullSecrets: []
# nameOverride: ubos-service-name
# fullnameOverride: ""

# serviceAccount:
#   create: true
#   name:

# service:
#   type: LoadBalancer
#   externalTrafficPolicy: Cluster
#   annotations: {}

# ports:
#   mqtt:
#     port: 1883
#     protocol: TCP
#   websocket:
#     port: 9090
#     protocol: TCP

# persistence:
#   enabled: true
#   accessMode: ReadWriteOnce
#   existingClaim: ""
#   mountPath: /mosquitto/data
#   subPath: ""
#   size: 1Gi

# resources: {}

# podSecurityContext: {}

# securityContext: {}

# nodeSelector: {}

# tolerations: []

# affinity: {}

# authentication:
#   passwordEntries: |-
#     ubos-service-mqtt-hesh-login
#   passwordFilePath: "/etc/mosquitto/passwordfile"

# authorization:
#   acls: ""
#   aclfilePath: "/etc/mosquitto/aclfile"

# existingConfigMap: ""
# config: |
#   persistence true
#   persistence_location /mosquitto/data/
#   log_dest stdout
#   listener 1883
#   listener 9090
#   protocol websockets

# extraVolumes: []
# extraVolumeMounts: []
# monitoring:
#   podMonitor:
#     enabled: false
#   sidecar:
#     enabled: false
#     port: 9234
#     image:
#       repository: nolte/mosquitto-exporter
#       tag: v0.6.3
#       pullPolicy: IfNotPresent
#     resources:
#       limits:
#         cpu: 300m
#         memory: 128Mi
#       requests:
#         cpu: 100m
#         memory: 64Mi
