# generic:
#   labels:
#     link: ubos-service-service_label
#   annotations: {}
#   extraSelectorLabels: {}
#   podLabels: {}
#   podAnnotations: {}
#   extraVolumes: []
#   extraImagePullSecrets:
#     - name: regcred
# podAffinityPreset: soft
# podAntiAffinityPreset: soft
# nodeAffinityPreset:
#   type: ''
#   key: ''
#   values: []
# releasePrefix: ''
# envs: {}
# envsString: ''
# secretEnvs: {}
# secretEnvsString: ''
# imagePullSecrets: {}
# defaultImage: nodered/node-red
# defaultImageTag: latest
# defaultImagePullPolicy: IfNotPresent
# deployments:
#   ubos-service-name:
#     name: ubos-service-service_label
#     labels: {}
#     podLabels: {}
#     replicaCount: "1"
#     nodeSelector: {}
#     tolerations: []
#     strategy:
#       type: Recreate
#     extraImagePullSecrets:
#       - name: regcred
#     extraSelectorLabels:
#       app: ubos-service-service_label
#     serviceAccountName: default
#     containers:
#       - name: ubos-service-service_label
#         image: postgres
#         imagePullPolicy: Always
#         env:
#           - name: POSTGRES_DB
#             value: ubos-service-name
#           - name: POSTGRES_USER
#             value: ubos-service-user-name
#           - name: POSTGRES_PASSWORD
#             value: ubos-service-password
#         envsFromSecret: {}
#         startupProbe:
#          tcpSocket:
#            port: 5432
#          failureThreshold: 30
#          periodSeconds: 10
#         readinessProbe:
#          tcpSocket:
#            port: 5432
#         envSecrets: []
#         envsFromConfigmap: {}
#         envConfigmaps: []
#         volumeMounts:
#           - name: ubos-service-service_label
#             mountPath: /data/db
#         resources: {}
#     volumes:
#       - type: pvc
#         name: ubos-service-service_label
#         items:
#           - key: ubos-service-service_label
#             path: ubos-service-service_label
# services:
#   ubos-service-name:
#     name: ubos-service-service_label
#     ports:
#       - port: 5432
#         targetPort: 5432
#         protocol: TCP
#     extraSelectorLabels:
#       app: ubos-service-service_label
#     type: ClusterIP
# ingresses: {}
# secrets: {}
# configMaps: {}
# pvcs:
#   ubos-service-service_label:
#     accessModes:
#       - ReadWriteOnce
#     size: 5Gi
# hooks: {}
# cronJobs: {}
# jobs: {}
# serviceMonitors: {}
# diagnosticMode:
#   enbled: false
#   command:
#     - sleep
#   args:
#     - infinity
# extraDeploy: {}
