{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-basic-auth
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  auth: {{ (printf "%s:%s" .Values.auth.username .Values.auth.password | b64enc) }}
{{- end }}
