apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-config
data:
  swagger-config.json: |
    {
      "urls": {{ toJson .Values.swaggerui.config.urls }},
      "plugins": [
        "topbar"
      ]
    }
