host: example.com # Доменне ім'я для інгресу
serviceName: my-service # Назва сервісу, який обробляє трафік
servicePort: 80 # Порт сервісу, на який інгрес буде перенаправляти трафік

# TLS та Cert-Manager конфігурація
tls: true # Увімкнути TLS
tlsSecretName: my-tls-secret # Назва секрету TLS
certManagerEnabled: true # Увімкнути Cert-Manager анотації
clusterIssuer: letsencrypt-prod # Ім'я кластерного видавця
